### ISSUE TITLE
Setting mainbar.y.label makes the package ignore scale.intersections

### ISSUE THREAD

**Issue by bjtrost** [hms-dbmi/UpSetR#84]
See title.  If you set scale.intersections="log10", it works as it should, but if you also set mainbar.y.label, scale.intersections="log10" is ignored.

**Comment by z-ninja-z** [comment]
I was having the same problem and figured I'd take a stab at solving it. I git cloned the repository and sourced all the R files then loaded all the required libraries so I could start changing things and troubleshooting.

```R
for (fh in list.files('~/Software/UpSetR/R/')) {
  source(paste0('~/Software/UpSetR/R/', fh))
}
library(plyr); library(ggplot2); library(grid); library(gridExtra); library(RColorBrewer)
```
But first, I ran `upset()` to make sure it was working and the error was reproducible. However, the problem doesn't seem to occur when using the cloned repository.

```R
movies <- read.csv( system.file("extdata", "movies.csv", package = "UpSetR"), header=T, sep=";" )
upset(movies, scale.intersections = "log2", mainbar.y.label = "Movie Count (log2)")
```
![movies](https://user-images.githubusercontent.com/14844211/29427320-440e3212-833e-11e7-8d1b-477986de1729.png)

It seems the CRAN distribution is significantly behind the development version. I'm not sure when the CRAN distribution was last updated or when it will next be updated.

If you just want to install the latest development version from github without worrying about cloning the repository, the readme recommends:

```R
devtools::install_github("hms-dbmi/UpSetR")
```

**Comment by brt381** [comment]
Thanks ninja! The problem was resolved after some back-and-forth by e-mail from the author of UpSetR, but I guess the fix has not yet made its way onto CRAN, as you note.

**Comment by JakeConway** [comment]
I will submit the latest dev version to CRAN this week

**Comment by mczulu** [comment]
I am using the CRAN version and still encounter this issue.  Additionally, I noticed a quirk in that scale.sets = log10 plots the set bars on a log scale, but scale.intersections = log10 converts the intersection values to log and then plots those values instead of plotting the original values on a log scale.  Is there any way to modify this?

Thanks!
